"""Mean-flux (tau0) rescaling of the Lya optical-depth field.

The emulator's mean-flux dimension is generated by post-processing the
optical depth tau. The physically-correct recipe ("freeze-core") rescales
optically-thin pixels by a factor alpha while *freezing* self-shielded
saturated cores (native tau > TAU_FREEZE_DEFAULT) at their native value:
self-shielded gas does not respond to the UV background. See
docs/superpowers/specs/2026-05-17-phase2-hcd-emulator-design.md sec. 3.

A uniform rescale ("Tier A", a deliberately-wrong systematic twin) is
recovered with tau_freeze = inf.
"""
from __future__ import annotations

import numpy as np

# Self-shielding freeze boundary. A native per-pixel Lya optical depth above
# this is a saturated DLA / strong-sub-DLA core (log N_HI >~ 19.3, verified)
# and is held fixed under rescaling. PRIYA's _filter_tau core threshold.
TAU_FREEZE_DEFAULT = 1.0e6

# Mean-flux factor grid: PRIYA's KODIAQ-slope range (coarse_grid.py).
ALPHA_LO_DEFAULT = 0.66
ALPHA_HI_DEFAULT = 1.36
N_ALPHA_DEFAULT = 20


def freeze_core_rescale(tau, alpha, tau_freeze=TAU_FREEZE_DEFAULT):
    """Rescale optically-thin pixels by `alpha`; freeze self-shielded cores.

    Parameters
    ----------
    tau : np.ndarray
        Native Lya optical depth (any shape). The freeze condition is
        evaluated on these native values.
    alpha : float
        Mean-flux multiplicative factor applied to non-frozen pixels.
    tau_freeze : float
        Pixels with native tau > tau_freeze keep their native value.
        Pass np.inf for a uniform rescale (Tier A).

    Returns
    -------
    np.ndarray
        Rescaled optical depth as float64, same shape as `tau`.
    """
    tau = np.asarray(tau, dtype=np.float64)
    return np.where(tau > tau_freeze, tau, alpha * tau)


def make_alpha_grid(n=N_ALPHA_DEFAULT, lo=ALPHA_LO_DEFAULT, hi=ALPHA_HI_DEFAULT):
    """Return `n` mean-flux factors, uniform in alpha over [lo, hi] inclusive."""
    if n < 2:
        raise ValueError(f"n must be >= 2, got {n}")
    return np.linspace(lo, hi, n)


def tau0_from_mean_flux(mean_flux):
    """Mean optical depth tau0 = -ln<F> from a (rescaled) state's clean <F>."""
    mf = float(mean_flux)
    if mf <= 0.0:
        raise ValueError(f"mean_flux must be > 0, got {mf}")
    return float(-np.log(mf))
