"""Per-mock corner-plot GALLERY for the STEP-A closures, split COSMO vs IGM, into a .md.

For every distinct closure fiducial with chains (checkpoints/stepA/<FID>_c*.npz), render two GetDist
triangles with truth markers (dashed):
  COSMO block : ns, Ap, alpha_LLS, alpha_subDLA, alpha_DLA  (cosmology + the HCD nuisances it is
                degenerate with — the science block of this analysis)
  IGM block   : herei, heref, alphaq, hub, omegamh2, hireionz, bhfeedback  (the 7 PRIYA astro params)
and write a grouped markdown gallery embedding them + a per-mock summary (n_s, bias_Ap, bias_ns).

bias_z = (truth - pooled_mean)/pooled_sd (the run_stepA battery convention).

ENV: getdist lives in emu-3.9. Run:
  /home/mfho/.conda/envs/emu-3.9/bin/python3 scripts/plot_corner_gallery.py
Optional: pass a space-separated FID list to restrict; default = all distinct completed mocks.
"""
import sys, glob, os, re
import numpy as np
import matplotlib; matplotlib.use("Agg")
from getdist import MCSamples, plots

CK = "checkpoints/stepA"
OUTDIR = "figures/analysis/05_likelihood/corner"
MD = "docs/superpowers/2026-06-11-corner-gallery.md"
os.makedirs(OUTDIR, exist_ok=True)

# training-box (PARAM_LIMITS) for unit->physical; Ap shown in 1e-9.
LIMS = {"ns": (0.8, 1.05), "Ap": (1.2e-9, 2.6e-9), "herei": (3.5, 4.5), "heref": (2.2, 3.2),
        "alphaq": (1.3, 3.0), "hub": (0.65, 0.75), "omegamh2": (0.14, 0.146),
        "hireionz": (6.5, 8.0), "bhfeedback": (0.03, 0.07)}
LAB = {"ns": r"n_s", "Ap": r"A_p[10^{-9}]", "alpha_lls": r"\alpha_{\rm LLS}",
       "alpha_subdla": r"\alpha_{\rm subDLA}", "alpha_dla": r"\alpha_{\rm DLA}",
       "herei": r"z_{\rm HeII,i}", "heref": r"z_{\rm HeII,f}", "alphaq": r"\alpha_q", "hub": "h",
       "omegamh2": r"\Omega_m h^2", "hireionz": r"z_{\rm HI}", "bhfeedback": r"\epsilon_{\rm BH}"}
COSMO = ["ns", "Ap", "alpha_lls", "alpha_subdla", "alpha_dla"]
IGM = ["herei", "heref", "alphaq", "hub", "omegamh2", "hireionz", "bhfeedback"]

# grouped presentation order for the md
GROUPS = [
    ("Phase-4 anchors (separate-inference, sim-mean center)", ["D_f3", "D_f4", "D_f6", "D_f7", "K_f4", "K_f6"]),
    ("HCD width / sensitivity arms (D_f6)", ["D_f6_lit", "D_f6_sig40", "D_f6_tau0x", "D_f6_sigL08",
        "D_f6_sigL25", "D_f6_sigL80", "D_f6_sigS020", "D_f6_sigS080", "D_f6_sigS150"]),
    ("IGM-parameter stress fiducials", ["IGM_herei_hi", "IGM_heref_lo", "IGM_heref_hi",
        "IGM_alphaq_lo", "IGM_alphaq_hi", "IGM_bhfb_lo"]),
    ("Per-survey LLS pin", ["D_lls", "D_lls_m", "D_lls_m30", "D_llsmed", "D_llsmed30", "K_lls"]),
    ("Multi-fold width check (matched center)", ["D_lmed3_15", "D_lmed3_30", "D_lmed5_15",
        "D_lmed5_30", "D_lmed7_15", "D_lmed7_30"]),
]


def to_phys(x, nm):
    if nm in LIMS:
        lo, hi = LIMS[nm]; v = lo + x * (hi - lo)
        return v * 1e9 if nm == "Ap" else v
    return x


def pool(fid):
    ps = sorted(p for p in glob.glob(f"{CK}/{fid}_c*.npz") if re.match(rf"{re.escape(fid)}_c\d+\.npz$", os.path.basename(p)))
    if not ps:
        return None
    packs, names, truth = [], None, None
    for p in ps:
        z = np.load(p, allow_pickle=True)
        names = list(z["names"]) if names is None else names
        truth = np.asarray(z["truth_vec"]) if truth is None else truth
        packs.append(np.asarray(z["packed"]))
    n = min(x.shape[0] for x in packs)
    return np.concatenate([x[:n] for x in packs], 0), names, truth, len(ps), float(np.load(ps[0], allow_pickle=True)["n_s"])


def corner(P, names, truth, block, fid, tag):
    cols = [to_phys(P[:, names.index(b)], b) for b in block]
    tv = [to_phys(truth[names.index(b)], b) for b in block]
    mcs = MCSamples(samples=np.column_stack(cols), names=block, labels=[LAB[b] for b in block])
    g = plots.get_subplot_plotter(width_inch=1.4 * len(block))
    g.settings.alpha_filled_add = 0.6
    g.triangle_plot([mcs], filled=True, markers={b: tv[i] for i, b in enumerate(block)},
                    marker_args={"color": "k", "lw": 1.0})
    out = f"{OUTDIR}/{fid}_{tag}.png"
    g.export(out); import matplotlib.pyplot as plt; plt.close("all")
    return out


def bias(P, names, truth, nm):
    j = names.index(nm); sd = P[:, j].std()
    return (truth[j] - P[:, j].mean()) / sd if sd > 0 else float("nan")


want = sys.argv[1:] if len(sys.argv) > 1 else None
md = ["# STEP-A closure corner gallery (cosmo vs IGM)\n",
      "*Auto-generated by `scripts/plot_corner_gallery.py`. Per mock: a COSMO corner "
      "(n_s, A_p + the HCD α nuisances they are degenerate with) and an IGM corner (the 7 PRIYA "
      "astro params). Dashed lines = truth. bias = (truth−post)/σ.*\n"]
done = set()
for title, fids in GROUPS:
    rows = []
    for fid in fids:
        if want and fid not in want:
            continue
        r = pool(fid)
        if r is None:
            continue
        P, names, truth, nc, ns = r
        c_png = corner(P, names, truth, COSMO, fid, "cosmo")
        i_png = corner(P, names, truth, IGM, fid, "igm")
        bA, bN = bias(P, names, truth, "Ap"), bias(P, names, truth, "ns")
        rel = lambda p: "../../" + p
        rows.append(f"### {fid}  (n_s={ns:.3f}, {nc} chains; bias A_p={bA:+.2f}σ, n_s={bN:+.2f}σ)\n\n"
                    f"![{fid} cosmo]({rel(c_png)})\n\n![{fid} IGM]({rel(i_png)})\n")
        done.add(fid)
    if rows:
        md.append(f"\n## {title}\n\n" + "\n".join(rows))
with open(MD, "w") as f:
    f.write("\n".join(md))
print(f"wrote {MD}  ({len(done)} mocks: {sorted(done)})")
