"""Manifest-pinned PRODUCTION ensemble loader (freeze decision 6, 2026-07-22).

WHY. The deployed drivers used to build the production member list with the permissive glob
``final_prod_seed*.eqx``: a stray ``final_prod_seed5.eqx`` dropped into the checkpoints dir
would silently JOIN the deployed ensemble at every call site, and a swapped/truncated binary
would load without complaint. The production ensemble is therefore pinned by a COMMITTED
machine-readable manifest (``checkpoints/production_ensemble_manifest.json``):

  * SHA256 for every member binary (.eqx, .norm.pkl, .meta.json);
  * an exact ORDERED member list (index 0..4, ``final_prod_seed<i>``);
  * explicit STRUCTURAL checkpoint<->normalizer pairing (the five .norm.pkl are
    byte-identical by construction, so pairing can NOT be digest-based: it is
    basename-per-index);
  * the expected member count (exactly ``N_PROD_MEMBERS`` = 5);
  * a FAIL-LOUD extra-member tripwire: any on-disk file matching the production prefix that
    is not in the manifest raises.

The binaries themselves are gitignored (they live only at ``/home/mfho/hcd_priya/checkpoints/``);
the committed manifest is their identity of record. The manifest is NEVER hand-edited: it is
regenerated by ``scripts/gen_ensemble_manifest.py`` (+ PI sign-off + a new analysis.lock).
Human-readable companion: ``checkpoints/README_production_ensemble.md``.

Digest verification hashes ~30 MB per load. That cost is deliberate (verify at every load;
no caching tricks). This module keeps its verification path pure-python (hashlib/json/glob);
the jax/equinox imports happen lazily inside ``load_production_ensemble`` only.
"""
from __future__ import annotations

import glob as _glob
import hashlib
import json
import os

# The production member basename prefix. This is the ONLY prefix the loader accepts; there is
# deliberately NO glob/prefix argument (an "alternate ensemble" cannot be swapped in by pointing
# a glob elsewhere -- replacement means regenerating the manifest, see the README).
PROD_BASENAME = "final_prod_seed"
N_PROD_MEMBERS = 5
MANIFEST_BASENAME = "production_ensemble_manifest.json"
MANIFEST_SCHEMA_VERSION = 1

# Repo root = two levels above this file's package dir; the committed manifest travels with
# the CODE tree (worktrees verify against the same pinned digests as the deployed tree).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_MANIFEST_PATH = os.path.join(_REPO_ROOT, "checkpoints", MANIFEST_BASENAME)

# Per-member files pinned BY DIGEST in the manifest. hist.json is git-tracked (git pins it),
# so it is listed in the manifest for provenance but not digest-verified here.
_DIGEST_KEYS = (("eqx", "eqx_sha256"), ("norm", "norm_sha256"), ("meta", "meta_sha256"))


class ProductionEnsembleError(RuntimeError):
    """A pinned-production-ensemble verification failure (missing/modified member, digest,
    pairing, count, ordering, or a stray production-prefix file not in the manifest)."""


def sha256_file(path, chunk_bytes=1 << 20):
    """Streaming SHA256 hex digest of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk_bytes), b""):
            h.update(block)
    return h.hexdigest()


def load_manifest(manifest_path=None):
    """Read the committed manifest JSON (no file verification -- see ``verify_manifest``)."""
    manifest_path = manifest_path or DEFAULT_MANIFEST_PATH
    if not os.path.exists(manifest_path):
        raise ProductionEnsembleError(
            f"production ensemble manifest not found at {manifest_path} -- the pinned member "
            f"list is REQUIRED (generate it with scripts/gen_ensemble_manifest.py)")
    with open(manifest_path) as f:
        return json.load(f)


def _expect(cond, msg):
    if not cond:
        raise ProductionEnsembleError(msg)


def verify_manifest(checkpoints_dir=None, manifest_path=None):
    """Verify the on-disk production ensemble against the committed manifest. Fail-loud.

    Asserts, in order:
      1. ``n_members == len(members) == N_PROD_MEMBERS`` (count);
      2. members are in EXACT index order 0..4 with ``name == final_prod_seed<i>`` (ordering);
      3. each member's eqx/norm/meta basenames are the exact structural pairing
         ``<name>.eqx / <name>.norm.pkl / <name>.meta.json`` (pairing; the five norm.pkl are
         byte-identical so pairing is structural, not digest-based);
      4. each pinned file EXISTS and its SHA256 matches the manifest (digest);
      5. NO stray file matching ``final_prod_seed*.eqx`` beyond the manifest set (tripwire).

    Returns ``(manifest, member_prefixes)`` where ``member_prefixes`` are the extensionless
    checkpoint paths (what ``train.load_checkpoint`` / ``ensemble.load_ensemble`` take), in
    manifest order.
    """
    manifest_path = manifest_path or DEFAULT_MANIFEST_PATH
    manifest = load_manifest(manifest_path)
    if checkpoints_dir is None:
        checkpoints_dir = os.path.dirname(os.path.abspath(manifest_path))

    members = manifest.get("members")
    _expect(isinstance(members, list),
            f"manifest {manifest_path} has no 'members' list (hand-edited or truncated?)")
    n = manifest.get("n_members")
    _expect(n == N_PROD_MEMBERS,
            f"manifest {manifest_path} pins n_members={n}, but the production ensemble is "
            f"pinned at exactly {N_PROD_MEMBERS} members (an intentional N change requires "
            f"regenerating the manifest AND updating prod_ensemble.N_PROD_MEMBERS + the "
            f"README + analysis.lock, with PI sign-off)")
    _expect(len(members) == n,
            f"manifest {manifest_path} member count mismatch: n_members={n} but the members "
            f"list has {len(members)} entries")

    prefixes = []
    for pos, mem in enumerate(members):
        idx = mem.get("index")
        _expect(idx == pos,
                f"manifest members OUT OF ORDER: position {pos} carries index {idx} "
                f"(expected ascending 0..{N_PROD_MEMBERS - 1}; member order is part of the "
                f"pinned identity -- do not reorder the manifest)")
        name = mem.get("name")
        want_name = f"{PROD_BASENAME}{pos}"
        _expect(name == want_name,
                f"manifest member {pos} name mismatch: expected {want_name!r}, got {name!r}")
        # STRUCTURAL pairing: <name>.eqx <-> <name>.norm.pkl (+ <name>.meta.json). The five
        # normalizers are byte-identical by construction, so a digest can not distinguish a
        # mis-pair; the basename-per-index pairing is the pinned contract.
        for key, want in (("eqx", name + ".eqx"), ("norm", name + ".norm.pkl"),
                          ("meta", name + ".meta.json")):
            got = mem.get(key)
            _expect(got == want,
                    f"manifest member {pos} ({name}) MIS-PAIRED {key}: expected {want!r}, "
                    f"got {got!r}")
        for key, sha_key in _DIGEST_KEYS:
            path = os.path.join(checkpoints_dir, mem[key])
            _expect(os.path.exists(path),
                    f"MISSING pinned production ensemble file: {path} (manifest member {pos}, "
                    f"{sha_key}={mem.get(sha_key)})")
            want_sha = mem.get(sha_key)
            _expect(isinstance(want_sha, str) and len(want_sha) == 64,
                    f"manifest member {pos} ({name}) has a malformed {sha_key}: {want_sha!r}")
            got_sha = sha256_file(path)
            _expect(got_sha == want_sha,
                    f"DIGEST MISMATCH for {path}: manifest expects sha256 {want_sha}, "
                    f"on-disk file is {got_sha} -- the pinned production member was modified "
                    f"or substituted")
        prefixes.append(os.path.join(checkpoints_dir, name))

    # manifest self-consistency: the byte-identical-normalizers statement must match the digests.
    if manifest.get("normalizers_byte_identical") is True:
        norm_shas = {mem["norm_sha256"] for mem in members}
        _expect(len(norm_shas) == 1,
                f"manifest claims normalizers_byte_identical=true but pins "
                f"{len(norm_shas)} distinct norm_sha256 values")

    # FAIL-LOUD EXTRA-MEMBER TRIPWIRE: any on-disk file matching the production prefix that is
    # not in the manifest must be detected, never ignored (the permissive-glob failure mode this
    # module exists to close: a stray final_prod_seed5.eqx would otherwise silently join the
    # deployed ensemble).
    pinned_eqx = {mem["eqx"] for mem in members}
    on_disk = sorted(os.path.basename(p)
                     for p in _glob.glob(os.path.join(checkpoints_dir, PROD_BASENAME + "*.eqx")))
    strays = [b for b in on_disk if b not in pinned_eqx]
    _expect(not strays,
            f"UNEXPECTED production-prefix checkpoint(s) in {checkpoints_dir} not pinned in the "
            f"manifest: {strays} -- a stray member must NEVER silently join the deployed "
            f"ensemble. Remove the stray file(s), or (intentional replacement ONLY) regenerate "
            f"the manifest via scripts/gen_ensemble_manifest.py + PI sign-off + a new "
            f"analysis.lock")

    return manifest, prefixes


def production_member_paths(checkpoints_dir=None, manifest_path=None):
    """The VERIFIED, ordered production member prefix paths (extensionless, what
    ``build_legb_ctx(ensemble_ckpts=...)`` consumes). Runs the full ``verify_manifest``
    battery (digests + pairing + count + order + stray tripwire) on every call."""
    _manifest, prefixes = verify_manifest(checkpoints_dir=checkpoints_dir,
                                          manifest_path=manifest_path)
    return prefixes


def load_production_ensemble(checkpoints_dir=None, manifest_path=None):
    """Verify (``verify_manifest``) then LOAD the pinned production ensemble.

    Returns ``(ensemble, meta0, norm0, manifest)``: the ``EnsembleEmulator`` over the five
    members in manifest order, member-0's meta and norm (the ``load_ensemble`` convention;
    it additionally asserts all members share the P_filt norm arrays), and the verified
    manifest dict.
    """
    manifest, prefixes = verify_manifest(checkpoints_dir=checkpoints_dir,
                                         manifest_path=manifest_path)
    from hcd_analysis.emulator.ensemble import load_ensemble  # lazy: pulls jax/equinox
    ensemble, meta0, norm0 = load_ensemble(prefixes)
    assert len(ensemble.members) == N_PROD_MEMBERS, \
        f"loaded {len(ensemble.members)} members from a verified {N_PROD_MEMBERS}-member manifest"
    return ensemble, meta0, norm0, manifest
