"""Gate E amendment A1 rev 1 section 7: the product manifest. Pins, by sha256, the products the production forward
reads (the gate D MF correction, the physical-k DLA core, the T1 and T3 emulator-error products, and T2 once amendment A2
registers it), and names the training cache and the production ensemble manifest they belong to. ``verify`` refuses any
digest mismatch, a different cache or ensemble, a missing required product or an unknown kind; it returns the paths
``build_legb_ctx`` consumes. Never hand-edited: regenerated by ``scripts/gen_product_manifest.py``."""
from __future__ import annotations

import hashlib
import json
import os

SCHEMA_VERSION = 1
KINDS = ("mf", "dla_core", "cemu_t1", "cemu_t2", "cemu_t3")
REQUIRED = ("mf", "dla_core", "cemu_t1", "cemu_t3")
T2_HELD = "held for PI ruling S14 (gate E amendment A1 rev 1 section 2); registered with amendment A2"


class ProductManifestError(RuntimeError):
    pass


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def build(paths, *, cache_sha256, ensemble_manifest_sha256):
    """The manifest dict for ``paths`` {kind: path} (cemu_t2 optional until amendment A2)."""
    unknown = sorted(set(paths) - set(KINDS))
    if unknown:
        raise ProductManifestError(f"unknown product kinds {unknown}")
    missing = [k for k in REQUIRED if not paths.get(k)]
    if missing:
        raise ProductManifestError(f"required products missing: {missing}")
    products, notes = {}, {}
    for k in KINDS:
        p = paths.get(k)
        if p is None:
            products[k] = None
            notes[k] = T2_HELD if k == "cemu_t2" else "absent"
            continue
        if not os.path.exists(p):
            raise ProductManifestError(f"{k}: {p} does not exist")
        products[k] = {"path": os.path.abspath(p), "sha256": sha256_file(p)}
    return {"schema_version": SCHEMA_VERSION, "cache_sha256": cache_sha256,
            "ensemble_manifest_sha256": ensemble_manifest_sha256, "products": products, "notes": notes}


def verify(manifest_path, *, cache_sha256, ensemble_manifest_sha256):
    """{kind: path or None} after checking schema, cache, ensemble and every digest."""
    with open(manifest_path) as f:
        m = json.load(f)
    if m.get("schema_version") != SCHEMA_VERSION:
        raise ProductManifestError(f"product manifest schema {m.get('schema_version')} != {SCHEMA_VERSION}")
    if m.get("cache_sha256") != cache_sha256:
        raise ProductManifestError("the products were built from another training cache")
    if m.get("ensemble_manifest_sha256") != ensemble_manifest_sha256:
        raise ProductManifestError("the products belong to another production ensemble manifest")
    out = {}
    for k in KINDS:
        e = m["products"].get(k)
        if e is None:
            if k in REQUIRED:
                raise ProductManifestError(f"required product {k} absent from the manifest")
            out[k] = None
            continue
        if not os.path.exists(e["path"]):
            raise ProductManifestError(f"{k}: pinned file {e['path']} is missing")
        got = sha256_file(e["path"])
        if got != e["sha256"]:
            raise ProductManifestError(f"{k}: sha256 {got} != pinned {e['sha256']}")
        out[k] = e["path"]
    return out
